config/routes.rb
Rails.application.routes.draw do
  resources :projects, except: [:show]
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]

  resources :search, only: [:index]

  root 'home#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  def self.search(search)
    if search
      where(['lower(name) LIKE ? OR lower(description) LIKE ?', "%#{search.downcase}%","%#{search.downcase}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

  has_many :memberships, dependent: :destroy
  has_many :projects, through: :memberships

  has_many :projects, dependent: :destroy

  validates_presence_of :username
  validates_uniqueness_of :username

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def self.search(search)
    if search
      where(['lower(name) LIKE ? OR lower(username) LIKE ? OR lower(about) LIKE ? OR lower(stack) LIKE ?', "%#{search.downcase}%","%#{search.downcase}%","%#{search.downcase}%","%#{search.downcase}%"])
    else
      all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :about, :github, :stack])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :about, :github, :stack])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.order(message_count: :desc).all
    @projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @users = User.all
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)
    @project.memberships.new(user: current_user)
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :link)
    end

    def authorize_user
      @project = current_user.projects.find_by(id: params[:id])
      redirect_to projects_path, notice: "Not authorized to edit this project" if @project.nil?
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
        @projects = Project.search(params[:search])
        @users = User.search(params[:search])
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include UsersHelper
  after_filter :update_information, only: [:create,:update]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
    def update_information
      data = get_first_info(@user.username)
      if data.present?
        @user.update(data)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.order(message_count: :desc).all
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def nav_link(text, path)
    options = current_page?(path) ? { class: "active pink item" } : { class: "item" }
    content_tag(:li, options) do
      link_to text, path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def user_in_project(project,user)
    for membership in project.memberships do
      if membership.user == user
        puts user.name
        return true
      end
    end
    false
  end

  def need_menu(project)
    not (user_in_project(project,current_user) and current_user != project.user and project.link.nil?)
  end
  
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
require 'net/http'
require 'json'
module UsersHelper

  @@api_link = "http://progconfbot.herokuapp.com/api/users/name/%s"
  @@info_link = "http://progconfbot.herokuapp.com/api/stat/%s/progConf"
  def get_first_info(username)
    link = @@api_link % [username]
    uri = URI(link)
    response = Net::HTTP.get(uri)
    data = JSON.parse(response)
    if data.present?
      { name:data["firstName"].to_s + (data["lastName"].present? ? " " + data["lastName"].to_s() :  ""),
       id: data["id"] }
    else
      nil
    end
  end

  def get_info(telegram_id)
    link = @@info_link % [telegram_id]
    uri = URI(link)
    response = Net::HTTP.get(uri)
    data = JSON.parse(response)
    if data.present?
      { name:data["user"]["firstName"].to_s + (data["user"]["lastName"].present? ? " " + data["user"]["lastName"].to_s() :  ""),
       message_count: data['messages'] }
    else
      nil
    end
  end
  
end

app/views/home/index.html.erb
<div class="body-content">
  <div class="ui container">
    <div class="ui grid">
      <div class="column twelve wide">
        <div class="ui link cards">
        <%for @user in @users%>
          <%= link_to @user, {class: "card"} do %>
            <div class="content">
              <div class="header"><%= @user.name %></div>
              <div class="meta"><%= @user.username %></div>
              <% if @user.about.present? %>
              <div class="description",>
              <%= @user.about %>
              </div>
              <% end %>
            </div>
            <% if @user.stack.present? %>
              <div class="extra content">
                <%= @user.stack %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        </div>

      </div>
      <div class="column four wide">
        <div class="ui segment">
          <h4 class="ui header">Projects</h4>

          <% for @project in @projects%>

            <%= link_to  @project.link.present? ? @project.link : projects_path, {class: "project"} do %>
              <div class="name"><%= @project.name %></div>
              <div class="users"><%= @project.memberships.count %> <i class="user icon"></i></div>
            <% end %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="ui attached inverted menu">
    <div class="ui container">
      <%= nav_link 'Home', root_path %>
      <%= nav_link 'Projects', projects_path %>

      <div class="right menu">
        <div class="item">
          <div class="ui transparent inverted icon input">
            <i class="search icon"></i>

            <%= form_tag search_index_path, :method => 'get' do%>
              <%= text_field_tag :search,nil, placeholder:"Search" %>
            <% end %>
          </div>
        </div>
        <% if user_signed_in? %>

        <div class="ui dropdown item" tabindex="0">
          <%= current_user.name %>
          <i class="dropdown icon"></i>
          <div class="menu transition hidden" tabindex="-1">
            <%= link_to 'Show profile', current_user, {class: 'item'}%>
            <%= link_to 'Edit profile', edit_user_registration_path, {class: 'item'} %>
            <%= link_to "Sign out", destroy_user_session_path,  {class: 'item', method: 'delete'} %>
          </div>
          
        </div>
        <% else %>
          <%= nav_link 'Sign in', new_user_session_path %>
          <%= nav_link 'Sign up', new_user_registration_path %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wilku</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/semantic-ui/2.2.10/semantic.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.10/semantic.min.css"> 
  </head>

  <body>
    <%= render :partial => "layouts/header" %>
    
    <% if not notice.nil? %>
      <div class="ui container body-content">
        <div class="ui positive message">
          <i class="close icon"></i>
          <%= notice %>
        </div>
      </div>
    <% end %>

    <% if not alert.nil? %>
      <div class="ui container body-content">
        <div class="ui error message">
          <i class="close icon"></i>

          <%= alert %>
        </div>
      </div>
    <% end %>
    <%= yield %>
    <script>
    $('.ui.dropdown').dropdown();
    </script>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project, html: { class: "ui form" })  do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder:"Project name" %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.url_field :link, placeholder:"Link to your project" %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder:"Short description" %>
  </div>

  <%= f.submit "Update", class: "button ui pink" %>
<% end %>

app/views/projects/edit.html.erb
<div class="body-content">
  <div class="ui container">    
    <div class="ui container three column centered grid">
      <div class="column">
        <h1>Editing Project</h1>
        <%= render 'form', project: @project %>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="body-content">
  <div class="ui container">
    <div class="ui grid ">
      <div class="column twelve wide ">
      <h1 class="ui header">Projects <%= link_to 'New Project', new_project_path, class:"ui pink button", style:"float:right" %></h1>
        <div class="ui items divided">
          <% for @project in @projects do %>
              <div class="item">
                <div class="content">
                  <div class="header"><%= @project.name %>
                    <% if need_menu(@project)%>
                      <div class="ui inline dropdown">
                        <i class="ellipsis vertical icon"></i>
                        <div class="menu">
                          <% if @project.link.present? %><a class="item" href=<%= @project.link%>>link to project</a><% end %>
                          <% if not user_in_project(@project,current_user)%> <%= link_to 'join project', edit_project_path(@project), class:"item"%> <% end %>
                          <% if @project.user == current_user %> <%= link_to 'edit project', edit_project_path(@project), class:"item"%>  <% end %>
                        </div>  
                      </div>
                    <% end %>
                  </div>
                  <div class="description">
                    <p><%= @project.description %></p>
                  </div>
                  <div class="extra">
                    <i class="black icon user"></i>
                    <% for @member in @project.memberships do %>
                    <%= link_to @member.user.name, @member.user, class:"user-link" %>
                    <%end%>
                  </div>
                </div>
              </div>
          <% end %>
        </div>

      </div>
      <div class="column four wide">
      <div class="ui segment">
          <h4 class="ui header">Users</h4>
          <% for @user in @users%>
            <%= link_to @user, {class: "project"} do %>
              <div class="name"><%= @user.name %></div>
              <div class="users"><%= @user.memberships.count %> <i class="users icon"></i></div>
            <% end %>
          <% end %>
        </div>
      
      </div>
    </div>

  </div>
</div>

<script>

$('.accordion')
  .accordion({
    selector: {
      trigger: '.title'
    }
  })
;
</script>

app/views/projects/new.html.erb
<div class="body-content">
  <div class="ui container">    
    <div class="ui container three column centered grid">
      <div class="column">
        <h1>New Project</h1>
        <%= render 'form', project: @project %>
      </div>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<div class="body-content">
  <div class="ui container">
        <% if @users.empty? and @projects.empty? %>
        <div class="header ui"> Nothing were found</div>
        <% end %>
        <% if @users.present? %> <h1 class="ui header">Users</h1> <% end %>
        <div class="ui link cards">
            <%for @user in @users%>
            <%= link_to @user, {class: "card"} do %>
              <div class="content">
              <div class="header"><%= @user.name %></div>
              <div class="meta"><%= @user.username %></div>
              <% if @user.about.present? %>
              <div class="description",>
              <%= @user.about %>
              </div>
              <% end %>
            </div>
            <% if @user.stack.present? %>
              <div class="extra content">
                <%= @user.stack %>
              </div>
            <% end %>
            <% end %>
            <% end %>
        </div>

        <% if @projects.present? %><h1 class="ui header">Projects</h1> <%end%>
        <div class="ui items divided">
          <% for @project in @projects do %>
              <div class="item">
                <div class="content">
                  <div class="header"><%= @project.name %>
                    <% if need_menu(@project)%>
                      <div class="ui inline dropdown">
                        <i class="ellipsis vertical icon"></i>
                        <div class="menu">
                          <% if @project.link.present? %><a class="item" href=<%= @project.link%>>link to project</a><% end %>
                          <% if not user_in_project(@project,current_user)%> <%= link_to 'join project', edit_project_path(@project), class:"item"%> <% end %>
                          <% if @project.user == current_user %> <%= link_to 'edit project', edit_project_path(@project), class:"item"%>  <% end %>
                        </div>  
                      </div>
                    <% end %>
                  </div>
                  <div class="description">
                    <p><%= @project.description %></p>
                  </div>
                  <div class="extra">
                    <i class="black icon user"></i>
                    <% for @member in @project.memberships do %>
                    <%= link_to @member.user.name, @member.user, class:"user-link" %>
                    <%end%>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="body-content">
  <div class="ui container">
    <div class="ui grid">
      <div class="column twelve wide">
        <div class="ui link cards">
          <%for @user in @users%>
            <%= link_to @user, {class: "card"} do %>
              <div class="content">
                <div class="header"><%= @user.name %></div>
                <div class="meta"><%= @user.username %></div>
                <div class="description">
                <% for tag in stack_tags(@user.stack) %><div class="ui label"><%= tag %></div><% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="column four wide">
        <div class="ui segment">
          <h4 class="ui header">Projects</h4>
          <% for @project in @projects%>
            <%= link_to @project, {class: "project"} do %>
            <div class="name"><%= @project.name %></div>
            <div class="users"><%= @project.memberships.count %>
              <i class="user icon"></i>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="body-content">
  <div class="ui container">


    <div class="ui grid">
      <div class="column five wide">
        <div class="ui card">
          <div class="ui image">
            <%# img src="https://semantic-ui.com/images/avatar2/large/kristy.png">%>
          </div>
          <div class="content">
            <a class="header"><%= @user.name %></a>
            <div class="meta">
              <span class="date"><%= @user.username %></span>
            </div>
          </div>
          <div class="extra content">
            <a>
              <i class="send icon"></i>
              <%= @user.message_count %> Messages
            </a>
          </div>
        </div>
      </div>
      <div class="column eleven wide">
        <div class="ui segment">
          <% if @user.stack.present? %>
          <h3 class="ui header">
            Stack
          </h3>
          <p class="about", style='white-space: pre-line;'><%= @user.stack %></p>
          <% end %>
          <% if @user.stack.present? and @user.about.present? %><div class="ui section divider"></div> <% end %>
          <% if @user.about.present? %>
          <h3 class="ui header">
            About
          </h3>
          <p class="about", style='white-space: pre-line;'><%= @user.about %></p>
          <% end %>

          


        </div>
      </div>

  </div>
</div>